apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deploy-cm
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: python-app-cm
  template:
    metadata:
      labels:
        app: python-app-cm
    spec:
      containers:
        - name: python-container-cm
          # image: vishwacloudlab/pythonapp:v4-var
          image: 640168426521.dkr.ecr.us-east-1.amazonaws.com/pythonapp:v1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: py-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

