apiVersion: v1
kind: Service
metadata:
  name: py-service-cm
spec:
  type: NodePort
  selector:
    app: python-app-cm
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30115
